social_clone/simplesocial/groups/urls.py
#Groups URL.def

from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [

    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>',views.LeaveGroup.as_view(),name='leave'),
    #publish post
    #path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),

]

social_clone/simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(), name="create"),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete')
]


#publish post
#path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),

social_clone/simplesocial/simplesocial/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    #connects project urls to app urls
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name="thanks"),

    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls', namespace="posts")),
    path('groups/',include('groups.urls', namespace='group')),

    ]

social_clone/simplesocial/groups/models.py
#GROUPS - models!
from django.conf import settings
#from django.core.urlresolvers import reverse
from django.urls import reverse

from django.db import models
#allows remove characters that are alphnumeric (eg. spaces in urls, allow to work with browser)
from django.utils.text import slugify

#allows link embedding - needs MS visual C++ 14.0
#import misaka

#returns user model currently active - allows call things off the current user session
from django.contrib.auth import get_user_model

User = get_user_model()

#users custom template tags
from django import template
register=template.Library()


class Group(models.Model):
    #name of the group
    name = models.CharField(max_length=255,unique=True)
    #slug representation of the group
    slug = models.SlugField(allow_unicode=True,unique=True)
    #description of the group
    description = models.TextField(blank=True,default='')
    #use to get markdown text
    description_html = models.TextField(editable=False,default='',blank=True)
    #list of members that below to the group
    members = models.ManyToManyField(User,through="GroupMember")

    #returns the group name
    def __str__(self):
        return self.name

    #used to save a new group
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        #self.description_html = misaka.html(self.description)
        self.description_html = self.description
        super().save(*args,**kwargs)

    #once a group is created - where is the user sent?
    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    #call to order the list of groups by alpha by name
    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    #group user belongs too
    group = models.ForeignKey(Group,related_name="memberships",on_delete=models.CASCADE)
    #user whos part of the group
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')
    #pass

social_clone/simplesocial/groups/views.py
#GROUPS!!

from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                       PermissionRequiredMixin)
#from django.core.urlresolvers import reverse
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import render

from django.shortcuts import get_object_or_404
from django.views import generic
#class based views
from groups.models import Group,GroupMember
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    #fields the user is able to edit
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group


#login is required to do this. Once you join a group it redirects you somewhere
class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    #once joined a group redirect to groups single detail page
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    #makes sure cant join a group if you're not already in it
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        #checks if already a member
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        #advises already member if exists already
        except IntegrityError:
            messages.warning(self.request,'Warning already a member')
        #else advise you've become a member
        else:
            messages.success(self.request,'You are now a member')

        return super().get(request,*args,**kwargs)


#login is required to do this. Once leave a group it redirects you somewhere
class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    #once leave a group redirect to groups single detail page
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    #makes sure cant leave a group if you're not already in it
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        #checks if already a member
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()

        #advises already member if exists already
        except models.GroupMember.DoesNotExist:
                messages.warning(
                    self.request,
                    'sorry you arent in this group'
                )
        #else advise you've become a member
        else:
            membership.delete()
            messages.success(
                self.request,
                'you have left the group'
            )

        return super().get(request, *args, **kwargs)

social_clone/simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <!--separates pregroup, group_content, postgroup in group .html files -->
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>
{% endblock %}

social_clone/simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

<!--call group.names field from groups model-->
<h1>{{group.name}}</h1>
<!--call group.members field from groups model. Count these-->
<h2>Member Count: {{group.members.count}}</h2>
<!--add leave or join button. If the user is a group member, give option to leave the group-->
<!--slug used to handle spaces-->
{% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}"
      class='btn btn-lg btn-fill btn-warning'><span
      class='glyphicon glyphicon-remove-circle'></span>Leave</a>
<!--if not in a group show option to join-->
{% else %}
    <a href="{% url 'groups:join' slug=group.slug %}"
      class='btn btn-lg btn-fill btn-warning'><span
      class='glyphicon glyphicon-ok-circle'></span>Join</a>

{% endif%}

{% endblock %}

{% block group_content %}

<div class="col-md-8">
  <!--if theres no posts show no posts message-->
  {% if group.posts.count == 0 %}
      <h2>No posts in the group yet!</h2>
  {% else %}
  <!--else show all of the posts in the group (_post.html)-->
    {% for post in group.posts.all %}
        <!-- use include to inject a html file to show the posts. include is similar to extends -->
        {% include "posts/_post.html" %}
    {% endfor %}
  {% endif %}

</div>

{% endblock %}

social_clone/simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

social_clone/simplesocial/groups/templates/groups/group_list.html
<!-- extend base formating -->
{% extends "groups/group_base.html" %}

<!-- -->
<!--show welcome back <username> if user is authenticated, welcome to the groups page-->
{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            <!--check if authenticated -->
            {% if user.is_authenticated %}
              <h2>Welcome Back
                <!--welcome back user. User pull from users post (in posts app)-->
                  <a href="{% url 'posts:for_user' username=user.username %}">
                    @{{user.username}}
                  </a>
              </h2>
            {% endif %}
            <!--for everybody (authenticated or not) - welcome to groups page-->
            <h2>Groups</h2>
            <p>Welcome to the groups page!</p>
        </div>
    <!--if user is authenticated allow user to create a link to "create a new group"-->
    {% if user.is_authenticated %}
        <a href="{% url 'groups:create'%}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus-sign">Create New Group!</span>
        </a>
    {% endif %}
    </div>
{% endblock %}

<!-- -->
{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
          <!--show each group in "object list" -->
          {% for group in object_list %}
              <a class = 'list-group-item' href="{% url 'groups:single' slug=group.slug %}">
                    <!--show group name -- as a link when click on group name it will take you to groups page -->
                    <h3 class="title list-group-item-heading">{{group.name}}</h3>
                    <div class="list-group-item-text container-fluid">

                    <!--safe enables bold or italics tags to be displayed correctly -->
                    {{group.description_html|safe}}
                          <div class="row">
                                <div class="col-md-4">
                                      <!--show a count of the group memebers-->
                                      <span class="badge">{{group.members.count}}</span>
                                      member{{group.members.count|pluralize}}
                                </div>
                                <!--show a count of the group posts-->
                                <div class="col-md-4">
                                      <span class="badge">{{group.posts.count}}</span>
                                      post{{group.posts.count|pluralize}}
                                </div>
                          </div>
                    </div>
              </a>
          {% endfor %}
        </div>
    </div>
{% endblock %}