social_clone/simplesocial/accounts/urls.py
#import django's path functionality from conf.urls
#from django.conf.urls import path
from django.urls import path

#login logout views are automatic (exists within Django)
from django.contrib.auth import views as auth_views

#import views from views.py
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    #uses default view
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    #uses Signup view in views.py
    path('signup/',views.SignUp.as_view(),name='signup'),

]

social_clone/simplesocial/groups/urls.py
#Groups URL.def

from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [

    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>',views.LeaveGroup.as_view(),name='leave'),
    #publish post
    #path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),

]

social_clone/simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(), name="create"),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete')
]


#publish post
#path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),

social_clone/simplesocial/simplesocial/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    #connects project urls to app urls
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name="thanks"),

    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls', namespace="posts")),
    path('groups/',include('groups.urls', namespace='group')),

    ]

social_clone/simplesocial/templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <!--bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!--bootstrap optional theme-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!--bootstrap javascript-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!--Fonts (https://fonts.googleapis.com/)-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <!--Custom CSS. link to blog.css file-->
    <link rel="stylesheet" href="{% static "simplesocial/css/master.css"%}"/>

  </head>

  <body>
      <nav class='navbar mynav' role='navigation' id='navbar'>
        <div class="container">
            <a class='navbar-brand mynav' href="{% url 'home' %}">Star Social</a>
                <ul class="nav navbar-nav navbar-right">
                  {% if user.is_authenticated %}

                    <!--posts (appname) create = url name -->

                        <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                        <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                        <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                        <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                  {% else %}
                        <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
                        <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                        <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
                  {% endif %}
                </ul>
        </div>

      </nav>

    <div class="container mycontent">

      {% block content %}
      {% endblock %}

    </div>

    <canvas id="canvas"></canvas>

  </body>

  <!--link to custom javascript-->
  <script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}">
  </script>




</html>

social_clone/simplesocial/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>welcome to star social</h1>
{% endblock %}

social_clone/simplesocial/templates/test.html
{% extends "base.html" %}

{% block content %}

<h1>you are now logged in</h1>

{% endblock%}

social_clone/simplesocial/templates/thanks.html
{% extends "base.html" %}

{% block content %}

<h1>thanks for visiting come back soon</h1>

{% endblock%}